### ISSUE TITLE
Missing _id

### ISSUE THREAD

**Issue by tbobm** [nesdis/djongo#36] opened 2017-12-27 14:58 UTC
#### Python script

```python
class SomeClass(models.Model):
    """"""
    class Meta:
        """SomeClass attributes."""
        managed = False
    pk = models.IntegerField(db_column='_id')
```

#### Issue

For some reason, the `sql2mongo.py@Result:next` method has the following lines:
```python
        if isinstance(cur, PymongoCursor):
            doc.pop('_id')
            if len(doc) == len(p_sql.proj.coll_fields):
                return tuple(doc.values())
```

If you don't mind, I'd like to remove the `doc.pop('_id')`, part of me doesn't understand why this line is present, another one wants to use djongo but having to manually fix this or fork the repository would be pretty overkill.
If this line is actually necessary, I'll find another way.

Thanks in advance for your work, I'll provide a pull request and link it to this issue, just in case.

(I'm refering to the 1.2.10 package on pypi)

**Comment by nesdis** [comment] 2017-12-27 15:33
Why do you want to use the _id field? It is something the Django ORM
doesn't expect. The ORM only recognizes the id auto key it creates for each
model.

Introducing the _id has the potential to break the ORM.

**Comment by tbobm** [comment] 2017-12-27 15:38
I need to use it, because it's a value "manually" defined in MongoDB in a project I'm working on.
I understand the risk, but having it silently disposed this way kind of surprised me.

A workaround would be to rename it, instead of popping it, I guess, or even to allow the user to chose, after having considered the consequences.

**Comment by nesdis** [comment] 2017-12-27 15:53
Are you saying the _id field in your project is not what mongodb automatically generates when a doc is inserted, instead it is manually added by u?

If that's the case. You are not using djongo orm to create new documents,  because there is no manual way to create _id using the ORM unless you have a column in your ORM named '_id'.

Mongodb as such doesnt recommend overriding the auto generated _id field (for sharding purpose). I personally feel just renaming the field in ur ORM to something other than _id is a good option. 

Which means if you have mongodb as the backend, assume _id is a reserved keyword for column name. 

Can you please explain to me what is your use case for which u need to override this field in your project?

**Comment by tbobm** [comment] 2017-12-27 16:06
Well, AFAIK MongoDB provides a default ObjectID [if the `_id` field is omitted](https://docs.mongodb.com/manual/core/document/#the-id-field), but I don't see this as overwriting.

My application isn't the only one accessing this database, so renaming the field isn't an option sadly.
I never read about the sharding purpose of the `_id` field in MongoDB, if I recall correctly the [shard keys](https://docs.mongodb.com/manual/sharding/#shard-keys) can be something else than an ObjectID, which I don't find to be the more suitable type to manage sharding.

I don't **need** to 'override' this field, I just need to be able to use it, or at least read it, either by making it a primary key-like attribute, or simply being allowed to change its name, or anything else really. I just need this field.

**Comment by nesdis** [comment] 2017-12-27 16:31
I have made a change to the code. You may wish to clone the latest version to check if it works for you now.

**Comment by tbobm** [comment] 2017-12-27 16:56
Well, I now have an issue when trying to use the latest commit.

```
  File "/srv/projects/app/.venv/lib/python3.6/site-packages/pymongo/pool.py", line 893, in get_socket
    sock_info.check_auth(all_credentials)
  File "/srv/projects/app/.venv/lib/python3.6/site-packages/pymongo/pool.py", line 588, in check_auth
    auth.authenticate(credentials, self)
  File "/srv/projects/app/.venv/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
    auth_func(credentials, sock_info)
  File "/srv/projects/app/.venv/lib/python3.6/site-packages/pymongo/auth.py", line 466, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/srv/projects/app/.venv/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/srv/projects/app/.venv/lib/python3.6/site-packages/pymongo/pool.py", line 496, in command
    collation=collation)
  File "/srv/projects/app/.venv/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/srv/projects/app/.venv/lib/python3.6/site-packages/pymongo/helpers.py", line 146, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
```

Didn't change credentials or anything, simply did the following:
```bash
pip uninstall djongo
pip install git+https://github.com/nesdis/djongo
```

My `settings.py` looks like the following:

```python
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': db_name,
        'USER': 'user',
        'PASSWORD': 'password'
    }
}
```

Any idea ?

**Comment by nesdis** [comment] 2017-12-28 04:19
you have not provided AUTH_SOURCE

**Comment by tbobm** [comment] 2017-12-28 10:15
Works like a charm. Would you mind making a release to pypi ?
Thanks a lot @nesdis !

**Comment by ravinarayansingh** [comment] 2017-12-28 17:06
@nesdis  any idea about nested  document something  like 
```
{
  "name": "xyz",
  "children": [
    {
      "name": "abc",
      "children": [
        {
          "name": "dcv",
          "children": [
            {
              "name": "Base Rate"
            }
          ]
        }
      ]
    }
  ]
}
```
self referencing model ?

**Comment by nesdis** [comment] 2017-12-28 17:25
@ravinarayansingh 

Please only post comments relevant to the issue under discussion. Please ensure the issue is  written in the format prescribed by the template. 

Thank you for your cooperation.

**Comment by ravinarayansingh** [comment] 2017-12-28 17:34
@nesdis sure thank you.

**Comment by nesdis** [comment] 2018-01-08 13:51
New version updated to pypi

**Comment by techdragon** [comment] 2018-01-09 08:17
Having read access to this value would also be useful for me. Its a little awkward to have the built in 'unique per document' value hidden when it comes time to create `__str__` values for some document types. 

```python
    def __str__(self):
        return "Foo: " + str(self.id)
```

Is an old habit that works quite well when no other obvious label is available. Djongo seems to return None in place of the Mongo ObjectID, for the `self.id` value.

**Comment by nesdis** [comment] 2018-01-09 12:38
I guess i reopened this issue by mistake. My bad. Closing it. 

Regarding getting the ObjectID u need to use '_id' for it, just 'id' gives auto id field

**Closed by nesdis** 2018-01-09 12:38 UTC

**Comment by stuboo** [comment] 2018-01-18 17:37
I suppose I don't really understand this statement:
> Regarding getting the ObjectID u need to use '_id' for it, just 'id' gives auto id field

If you try to call this inside a template, then there's an error with template rendering.

**Error**: Variables and attributes may not begin with underscores: 'u._id'

```
{% extends "fbn/header.html" %}

{% block content %}
    {% for u in object_list %}
        <p>{{ u._id }}: {{ u.fname }}, {{ u.lname }} -- {{ u.phone }}</p>
    {% endfor %}

{% endblock %}
```

**Comment by nesdis** [comment] 2018-01-19 02:23
Mongodb adds an internal field for every document you insert. The field is
named '_id' and the value is the ObjectID. If you what to access this in
your model create a attribute with '_id'.

Apart from this Django itself internally creates an 'id' attribute for your
models which dont have a primary key defined. For most people the id field
would be more relevant which is just an integer.

If you want to render the ObjectID in a template I still need to add
support for that...

This ticket is part of the enhancement project. I will get around to
implement it sometime soon.

**Comment by sandguardian** [comment] 2018-02-20 20:42
@nesdis Is it possible to query by _id field? I tried, but it returned empty result

**Comment by nesdis** [comment] 2018-02-22 02:31
Querying with _id as the primary key works. other ways like by using filter should also work fine. can you reproduce the issue with a script for me?

**Comment by valeriozhang** [comment] 2018-02-27 02:00
how do you query with _id? I can't seem to do model.object.get(id=ObjectID(standinid))?

**Comment by shaikhhafizf** [comment] 2020-09-04 04:27
Id field is not Genrating automatically when I am creating new object and save it  from Django admin GUI.
I have attached img of my model class 
![image](https://user-images.githubusercontent.com/59253733/92199475-ea32f500-ee94-11ea-9f53-7ba4d087c57e.png)

**Comment by itssuryaprasanth** [comment] 2023-09-01 15:15
> nesdis @nesdis 
Mongodb adds an internal field for every document you insert. The field is
named '_id' and the value is the ObjectID. If you what to access this in
your model create a attribute with '_id'.

Apart from this Django itself internally creates an 'id' attribute for your
models which dont have a primary key defined. For most people the id field
would be more relevant which is just an integer.

If you want to render the ObjectID in a template I still need to add
support for that...

This ticket is part of the enhancement project. I will get around to
implement it sometime soon.

Are you working on this? It's been a long-time and there is no proper fix anywhere for this issue.
