### ISSUE TITLE
Cannot correctly set primary key

### ISSUE THREAD

**Issue by yanina-kalinicheva** [nesdis/djongo#8] opened 2017-09-07 08:02 UTC
Hello! Thank you for this driver, I'm using it for my project, but I encounter a weird error which I cannot solve for a long time. Sorry if the mistake is on my side, but I hope you can help me out.

So I'm creating a webpage to add/delete documents from the database. I use simple `.save()` and `.delete()` functions in my views. But I face something that seems to be a collision between django and mongodb ids. If I don't include id to my model, then upon creation it's automatically added as an ObjectID and the document is created in the database with no error. However, if I try to delete it later either by `.delete()` from the webpage or in admin panel I have an error ("AssertionError DevList object can't be deleted because its id attribute is set to None" on the webpage or "Dev list with ID "None" doesn't exist. Perhaps it was deleted?" when just clicking on it in admin panel) Calling d.pk also results in "None". In the database _id exists.

Then I tried to assign `primary_key=True` to one of the fields and this time I can delete successfully, I can access the document from the admin panel, but I cannot create a new one (no error, but the document I'm trying to create is not added to the DB).

Finally, I created another attribute `_id = models.AutoField(primary_key=True)`. This time I can create (from both webpage and admin panel), pk = ObjectID, but when I try to delete I have errors again ("TypeError int() argument must be a string, a bytes-like object or a number, not 'ObjectId' " from webpage and "Dev list with ID "59b0f75b1d41c81ee13a7153" doesn't exist. Perhaps it was deleted?" from admin panel). Running `d.pk` returns correct ID in this case (still being ObjectID even though AutoField is supposed to be int), but `d._get_pk_val()` returns None.
Also if I create an int ID and then add `_id = models.AutoField(primary_key=True)` line, when I try to delete this int ID document from webpage I have no errors, but the document is not deleted from the database.

My model is:
```
class DevList(models.Model):
    dev_num = models.CharField(max_length = 200)
    dev_name = models.CharField(max_length = 200)
    dev_descr = models.CharField(max_length = 200)
    dev_type = models.CharField(max_length = 200)
```
Hope this information is enough. Thank you!

**Comment by nesdis** [comment] 2017-09-07 08:32
Will reproduce this issue and get back to you. ASAP

**Comment by nesdis** [comment] 2017-09-10 10:16
Is it possible to copy and paste the script you are using for this issue? along with the traceback. Creating and saving models is working fine for me.

**Comment by yanina-kalinicheva** [comment] 2017-09-11 02:16
Thank you for checking it. Is it possible that I'm missing some kind of libraries or settings? This is my first Django and MongoDB project, so I might have missed something. But I did follow the tutorials, and read a lot of documentations.
Even the simplest thing doesn't work for me. I attach my model.py and admin.py. In this test app I didn't even add any lines into my views, and still I have the same problem in the admin panel: I can create and object, but cannot access it. When clicking on any created (and existing in the db) object I still got "Testmodel with ID "None" doesn't exist. Perhaps it was deleted?" error.
As views are empty here's my models.py:
```
from django.db import models

# Create your models here.

class testmodel(models.Model):
    one = models.IntegerField()
    two = models.IntegerField()
```

And admin.py:
```
from django.contrib import admin

# Register your models here.

from .models import testmodel

admin.site.register(testmodel)
```

There are nothing else inside of these files. It's that simple.

On the following pictures I tried to (1) create a model (successfully), after clicking save button I was redirected to (2), then tried  to click "testmodel object" in a "The testmodel "testmodel object" was added successfully." but got error (3). And finally tried to click on any testmodel object in a list, but always had "Testmodel with ID "None" doesn't exist. Perhaps it was deleted?"

No other errors were produced either by terminal or by browser. The terminal traceback:
```
Performing system checks...

System check identified no issues (0 silenced).
September 11, 2017 - 02:10:33
Django version 1.11.3, using settings 'testproject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[11/Sep/2017 02:10:39] "GET /admin/ HTTP/1.1" 200 5640
[11/Sep/2017 02:10:39] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[11/Sep/2017 02:10:39] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[11/Sep/2017 02:10:39] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[11/Sep/2017 02:10:39] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[11/Sep/2017 02:10:39] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[11/Sep/2017 02:10:43] "GET /admin/testapp/testmodel/add/ HTTP/1.1" 200 4289
[11/Sep/2017 02:10:43] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[11/Sep/2017 02:11:00] "POST /admin/testapp/testmodel/add/ HTTP/1.1" 302 0
[11/Sep/2017 02:11:01] "GET /admin/testapp/testmodel/ HTTP/1.1" 200 5631
[11/Sep/2017 02:11:01] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[11/Sep/2017 02:11:11] "GET /admin/testapp/testmodel/59b5f0b41d41c8127a743dd1/change/ HTTP/1.1" 302 0
[11/Sep/2017 02:11:11] "GET /admin/ HTTP/1.1" 200 6069
[11/Sep/2017 02:11:18] "GET /admin/testapp/testmodel/ HTTP/1.1" 200 5411
[11/Sep/2017 02:11:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[11/Sep/2017 02:11:21] "GET /admin/testapp/testmodel/None/change/ HTTP/1.1" 302 0
[11/Sep/2017 02:11:21] "GET /admin/ HTTP/1.1" 200 6049
```

And the database:
```
{ "_id" : ObjectId("59a922061d41c8124d03c200"), "one" : 1, "two" : 2 }
{ "_id" : ObjectId("59a922bc1d41c81319324b91"), "one" : 4, "two" : 5 }
{ "_id" : ObjectId("59b5e5581d41c80e8ecb98bf"), "one" : 5, "two" : 2 }
{ "_id" : ObjectId("59b5e5f11d41c80e8ecb98ce"), "one" : 7, "two" : 7 }
{ "_id" : ObjectId("59b5e7d61d41c80e8ecb98d9"), "one" : 99, "two" : 99 }
{ "_id" : ObjectId("59b5ee131d41c80e8ecb98f7"), "one" : 535, "two" : 533 }
{ "_id" : ObjectId("59b5ef601d41c81205308def"), "one" : 5365, "two" : 5358 }
{ "_id" : ObjectId("59b5f0b41d41c8127a743dd1"), "one" : 777, "two" : 777 }
```
All the objects I've tried to add are there.

![1](https://user-images.githubusercontent.com/6967502/30255989-ea8b5d8c-96d9-11e7-9049-7625a3e115fa.png)
![2](https://user-images.githubusercontent.com/6967502/30255992-eae084ce-96d9-11e7-8b99-ea875f754a10.png)
![3](https://user-images.githubusercontent.com/6967502/30255990-ea950ba2-96d9-11e7-826a-e395d29aaa36.png)
![4](https://user-images.githubusercontent.com/6967502/30255991-ea96591c-96d9-11e7-82d7-038d420bb35c.png)

**Comment by yanina-kalinicheva** [comment] 2017-09-15 08:39
I really don't want to switch to other django mongodb extensions as djongo seems to be the most reliable and convenient. But I cannot solve this issue and unfortunately it's critical. Is it possible that something wrong with my system settings? I've checked all the requirements, but they seem to be fine. I'm running it on ubuntu 16.04.3 64 bit, I use Python 3.6.2, pymongo 3.5.1, sqlparse 0.2.3, django 1.11.3. Is there anything else I should check/do?
Thank you again!

**Comment by nesdis** [comment] 2017-09-15 09:59
Hello Yanina

There could be an issue in creating models via the admin GUI. This was tested and was working fine, but something may have broken after recent commits (Not sure). At the moment there are not too many people contributing to this project and I am having a hard time!!! 

I am sorry about not being able to address your issue faster. 

For the moment I can suggest creating your models directly (instead of using GUI admin) using a python script.... The model save() delete() etc all work fine when done directly from the script.

I am sure you are an excellent python programmer and I cordially **invite you to hack into djongo** in any which way and make changes. Your contributions will be gratefully acknowledged on the home page!! 

I am pleased to know you feel this is a good project and your encouragement means a lot!

It will take me another week to get to the root cause of your issue. Sorry for the delay.

**Comment by yanina-kalinicheva** [comment] 2017-09-15 10:29
Hi!
I understand how busy you are and thank you for doing it anyway.

But I don't think that problem is in admin  GUI because I have the same issue even with save() and delete() from script. This is how I do it:

```
def check_add(request):
    newone = NewList()
    newone.one = 38452145
    newone.two = 47684536
    newone.save()
    return HttpResponse(newone.pk)

def check_delete(request):
    oldone = NewList.objects.get(one = '38452145')
    oldone.delete()
    return redirect('index')
```
Models:
```
class NewList(models.Model):
    one = models.IntegerField()
    two = models.IntegerField()
```

The first def returns a valid pk and really saves it. But the second def (check_delete) returns 
```
AssertionError at /device_list/check_delete
NewList object can't be deleted because its id attribute is set to None.
```
So it's all the same thing, `pk` returns correct ID but `_get_pk_val()` always returns `None` no matter if it was called directly from the script or from the admin panel. 

I will appreciate if you could look into it and see why it's not working as it should. Unfortunately, I'm not that good with python or django yet, but I'm trying my best to learn and also trying to find out how to solve the issue I have. If I find any solution soon I will post it here or make a contribution.

I know that this issue is very strange, again thank you so much for even reading this!
I will wait for your reply, hopefully this issue can be solved.

**Comment by nesdis** [comment] 2017-09-19 04:39
Hello

I have been trying to get the help of the [MongoDB community](https://groups.google.com/forum/#!topic/mongodb-dev/6rk0P-198D4) in helping out to complete this project faster. 

Looks to me MongoDB is simply not interested in investing its own resources for this project. MongoDB is a highly funded org which seems to have other priorities as indicated by its Director of engineering. 

Community support is required for adding all the features. I believe your issue will be eventually fixed! There are other issues in this project which i am working on currently.

Once again thank you for your support!

**Comment by nesdis** [comment] 2017-09-19 05:36
Hi

Can you tell me what your database (MongoDB) looks like after you execute these commands:

```python

def check_add(request):
    newone = NewList()
    newone.one = 38452145
    newone.two = 47684536
    newone.save()

```
When I do this, I get ['_id', 'id', 'one', 'two'] as my fields. 

Next i do `tdel = NewList.objects.get(one = 38452145)` followed by `tdel.delete()` Works with no issue

**Comment by nesdis** [comment] 2017-10-07 15:39
I think most of the issues with using admin and registered models are now fixed... I am able to do all model related manipulations from the GUI.

Closing this issue. You can open it if you find another bug

**Closed by nesdis** 2017-10-07 15:39 UTC

**Comment by paulwinex** [comment] 2018-12-17 06:39
Hi
I just start use djongo and already have saving problem.
I have no chance to fix it myself, maybe you can help me?
The problem: 
In settings i set 'ENFORCE_SCHEMA': False, because i dont want call migrate any time. It is the main reason why i use mongo!
On project init i call **makemigrations + migrate** to create init collections.
Later any new model adds data to database just fine, but without **id** field!
If i call **makemigratiosn app + migrate app** before models creation it fix the problem, but i dont want  to call migrations every time! Creation from code or from admin UI not fix this probjem, only migrations before first object created.
So, what i should do to create auto field ID without migrations? Maybe i must to do some specific steps?

**Comment by paulwinex** [comment] 2018-12-22 11:51
This is my temporary fix, abstract class for all my models

```
class MongoModel(models.Model):
    id = models.IntegerField(primary_key=True)
    class Meta:
        abstract = True
    def save(self, *args, **kwargs):
        if self.id is None:
            self.id = self.__class__.objects.count()
        super(MongoModel, self).save(*args, **kwargs)

```
For default Django models like User or Group still need migration in first time.

**Comment by paulwinex** [comment] 2018-12-22 19:30
Update with incremented unique id
I think djongo should do something like this

```
client = MongoClient(settings.DATABASES['default']['HOST'], settings.DATABASES['default']['PORT'])
db = client[settings.DATABASES['default']['NAME']]

class MongoModel(models.Model):
    id = models.IntegerField(primary_key=True)
    class Meta:
        abstract = True
    def save(self, *args, **kwargs):
        if self.id is None:
            self.id = self.__get_id()
        super(MongoModel, self).save(*args, **kwargs)

    def __get_id(self):
        name = self.__class__.__name__
        if not db.sequences.find_one(dict(name=name)):
            db.sequences.insert_one(dict(name=name, next_id=1))
            return 0
        else:
            sq = db.sequences.find_one_and_update({"name": name}, {"$inc": {"next_id": 1}})
            return sq['next_id']

```

**Comment by haroldw** [comment] 2020-07-10 19:30
I run into the same problem. ID returns as ObjectID instead. No clear solution yet.

`class Test(models.Model):
    a = models.IntegerField()
`
`
$ python manage.py shell
DEVELOPMENT
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from api.models import Test                                                                                                                                                                                                                                           

In [2]: Test.objects.create(a=2).pk                                                                                                                                                                                                                                           
Out[2]: ObjectId('5f08c18c10cc72a4921e42a0')
`

**Comment by ngdcminhuet** [comment] 2020-10-26 10:25
i have the same issue. Hope someone can fix it

**Comment by chiraag-kakar** [comment] 2020-11-07 19:27
Hey, @ngdcminhuet I too faced this issue while I used id as Autofield type primary. 
However, I was able to fix the issue by using a new type called UUID (which was introduced in Django 1.8+) as follows
 
Step 1 
```pip install uuid``` 

Step 2
Then imported it into the models.py file by adding the following line before model class
```import uuid```

Step 3
Example Showing how to use UUID field instead of Integer or Auto Field for storing object id : 
```
import uuid
from django.db import models

class Event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```


I hope it helps!

@nesdis  Kudos for building djongo !

**Comment by FilipProgrammer** [comment] 2021-06-15 21:51
Thanks for this, I wish djongo  have better documentation.
