### ISSUE TITLE
ArrayReferenceField Does not Work

### ISSUE THREAD

**Issue by thestick613** [nesdis/djongo#235] opened 2019-02-02 12:56 UTC
I think #225 is right, this does not work:

```
class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Entry(models.Model):
    headline = models.CharField(max_length=255)
    body_text = models.TextField()

    authors = models.ArrayReferenceField(
        to=Author,
        on_delete=models.CASCADE,
    )

from django.contrib import admin
from .models import Author, Entry
admin.site.register(Author)
admin.site.register(Entry)

```

Editing an Entry from admin raises this traceback
`Exception Value: int() argument must be a string, a bytes-like object or a number, not 'set'
`

If you alter the Author model like this,

```
class Author(models.Model):
    _id = models.CharField(max_length=256, primary_key=True)
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name

```

You get a different error,

`author instance with _id set() does not exist.
`

**Comment by abawchen** [comment] 2019-02-21 01:55
I encounter the same issue :(

**Comment by teamhide** [comment] 2019-03-05 05:54
Same issue here.

**Comment by Balagii** [comment] 2019-03-18 21:13
same issue here

**Comment by nesdis** [comment] 2019-03-30 18:16
I have now made changes to fix this bug. The changes are on the dev branch: bugfix_235. 

Do get back to me with your comments.

**Comment by thestick613** [comment] 2019-04-02 10:13
Everything i tested works. This is great! I believe your branch fixes #235, #207 and #225. This even works flawlessly with `django-autocomplete-light`'s `dal.autocomplete.Select2Multiple` widget.

**Comment by thestick613** [comment] 2019-04-02 15:48
```
class Author(models.Model):
    name = models.CharField(max_length=200, db_column="_id", primary_key=True)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Entry(models.Model):
    headline = models.CharField(max_length=255)
    body_text = models.TextField()

    authors = models.ArrayReferenceField(
        to=Author,
        on_delete=models.CASCADE,
        blank=True,
    )

    last_edited = models.ForeignKey(Author, on_delete=models.DO_NOTHING)
```

This raises the following error:

```
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
myapp.Entry.authors: (fields.E304) Reverse accessor for 'Entry.authors' clashes with reverse accessor for 'Entry.last_edited'.
	HINT: Add or change a related_name argument to the definition for 'Entry.authors' or 'Entry.last_edited'.
myapp.Entry.last_edited: (fields.E304) Reverse accessor for 'Entry.last_edited' clashes with reverse accessor for 'Entry.authors'.
	HINT: Add or change a related_name argument to the definition for 'Entry.last_edited' or 'Entry.authors'.

System check identified 2 issues (0 silenced).
```

This is fixable by adding a `related_name` to one of the two fields, but i'm not 100% sure that the behaviour is expected.

**Comment by thestick613** [comment] 2019-04-10 14:29
Upon further review, i've found a bug:


```
class Author(models.Model):
    name = models.CharField(max_length=200, db_column="_id", primary_key=True)

class Newspaper(models.Model):
    name = models.CharField(max_length=200, db_column="_id", primary_key=True)
    authors = models.ArrayReferenceField(
        to=Author,
        on_delete=models.CASCADE,
        blank=True,
    )
```

If you add a Newspaper with a blank authors field - empty array: [], select_related stops working:

```
In [1]: from myapp.models import Newspaper                                                                                                                                                                                     

In [2]: qs = Newspaper.objects.filter()                                                                                                                                                                                        

In [3]: n = qs.get()                                                                                                                                                                                                          

In [4]: n.authors                                                                                                                                                                                                             
Out[4]: <djongo.models.fields.create_forward_array_reference_manager.<locals>.ArrayReferenceManager at 0x10a8a74a8>

In [5]: str(n.authors)                                                                                                                                                                                                        
Out[5]: 'myapp.Author.None'

In [6]: n.name                                                                                                                                                                                                                
Out[6]: 'Newspaper2'

In [7]: str(qs.query)                                                                                                                                                                                                          
Out[7]: 'SELECT "myapp_newspaper"."_id", "myapp_newspaper"."authors_id" FROM "myapp_newspaper"'

In [8]: qs                                                                                                                                                                                                                     
Out[8]: <QuerySet [<Newspaper: Newspaper object (Some Newspaper)>]>

In [9]: qs.query.select_related = True                                                                                                                                                                                         

In [10]: str(qs.query)                                                                                                                                                                                                          
Out[10]: 'SELECT "myapp_newspaper"."_id", "myapp_newspaper"."authors_id", "myapp_author"."_id", "myapp_author"."email" FROM "myapp_newspaper" INNER JOIN "myapp_author" ON ("myapp_newspaper"."authors_id" = "myapp_author"."_id")'

In [11]: qs                                                                                                                                                                                                                     
Out[11]: <QuerySet []>

```

**Comment by thestick613** [comment] 2019-04-13 13:14
If i declare the authors like this, with **null=True**:

    authors = models.ArrayReferenceField(
        to=Author,
        on_delete=models.CASCADE,
        blank=True,
        null=True

The select_related trouble goes away.

**Comment by nesdis** [comment] 2019-04-14 07:40
I think the issue is setting blank=TRUE, ArrayRefereceField (ARF) has not been tested with this yet.

**Comment by nesdis** [comment] 2019-04-26 19:21
I guess what is posted here after fixing the older issue is a new and different issue. I will close this one, as ARF is now working.

**Closed by nesdis** 2019-04-26 19:21 UTC

**Comment by abawchen** [comment] 2019-04-30 08:11
@nesdis : it seems not worked on master or `1.2.32`, correct me if I am wrong.
Thanks.
